update: use matrix on action tests

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -71,9 +71,17 @@ jobs:
           name: bundle
           path: dist
 
-  tests--test-a-affected:
+  action-tests:
     runs-on: ubuntu-latest
     needs: [build]
+
+    strategy:
+      matrix:
+        include:
+          - branch: test/test-a-affected
+            workspace: test-a
+            base: master
+            affected: true
 
     steps:
       - uses: actions/checkout@v2
@@ -89,26 +97,32 @@ jobs:
         with:
           repository: julien-capellari/test-is-workspace-affected
           path: test-repo
-          ref: test/test-a-affected
+          ref: ${{ matrix.branch }}
 
-      - name: Test is affected
+      - name: is-workspace-affected
         id: affected
         uses: ./
         with:
           project-root: test-repo
-          workspace: test-a
-          base: master
+          workspace: ${{ matrix.workspace }}
+          base: ${{ matrix.base }}
 
-      - name: Failed
-        if: ${{ !steps.affected.outputs.affected }}
+      - name: Should be affected
+        if: ${{ matrix.affected && !steps.affected.outputs.affected }}
         run: |
-          echo "::error::Test failed: workspace test-a should be affected affected"
+          echo "::error::Test failed: workspace ${{ matrix.workspace }} should be affected"
+          exit 1
+
+      - name: Should not be affected
+        if: ${{ !matrix.affected && steps.affected.outputs.affected }}
+        run: |
+          echo "::error::Test failed: workspace ${{ matrix.workspace }} should not be affected"
           exit 1
 
   deploy:
     if: github.event_name == 'push'
     runs-on: ubuntu-latest
-    needs: [tests--test-a-affected]
+    needs: [action-tests]
 
     steps:
       - uses: actions/checkout@v2
